import ReduxProvider from "@/store/provider";
import QueryProvider from "./_lib/queryProvider";
import "@/scss/index.scss";
import Header from "./_components/layout/Header";
import Footer from "./_components/layout/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, loading }) {
  return (
    <html lang="ko">
      <body>
        <QueryProvider>
          <ReduxProvider>
            <Header />
            {loading}
            {children}
            <Footer />
          </ReduxProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
