import ReduxProvider from "@/store/provider";
import QueryProvider from "./_lib/queryProvider";
import "@/scss/index.scss";
import Header from "./_components/layout/Header";
import Footer from "./_components/layout/Footer";
import PrefetchElement from "./_lib/prefetch";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, loading }) {
  return (
    <html lang="ko">
      <body tabIndex="0">
        <QueryProvider>
          <PrefetchElement
            url="/menus"
            keyValue={["header", "menus"]}
          >
            <Header />
          </PrefetchElement>
          {loading}
          {children}
          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}
